### ISSUE TITLE
Incredibly useful but a timezone issue

### ISSUE THREAD

**Issue by rgdobie** [ssddanbrown/sslcheck#2]
Hi ssddanbrown, 

I found this incredibly useful and adapted it run directly from the browser. 

One small issue I found was that the certificates are operating in UTC whereas the $now date is in local time. 
I made a change to show hours remaining when less than one day and this highlighted the issue.

The fix was simple: $now = new DateTime(UTC);

Regards
Richard Dobie

**Comment by ssddanbrown** [comment]
Thanks @rgdobie for the feedback and thanks for reporting this issue.

I've now applied the fix in 04dcad9b0476be18a96a983661f8b045efc05b57.
