### ISSUE TITLE
FAILED TO GET CERTIFICATE INFORMATION

### ISSUE THREAD

**Issue by lukejtm** [ssddanbrown/sslcheck#3]
I receive the below error when attempting to run this for my customer. Any ideas?

------------------------------------------------------------
Errors:

mail.customer.com.au:ipaddress :: FAILED TO GET CERTIFICATE INFORMATION
------------------------------------------------------------

**Comment by ssddanbrown** [comment]
@lukejtm I'd guess that a certificate could not be found or it could not be parsed. Not sure I can provide much more guidance or debugging without knowing the domain.

**Comment by lukejtm** [comment]
I resolved the issue by enabling TLS1.0 in my openssl.conf
