### ISSUE TITLE
Would be nice if it only sends email when..

### ISSUE THREAD

**Issue by ozgurerdogan** [ssddanbrown/sslcheck#4]
Would be nice if it only sends email when cert is xx days to next renewal date.

**Comment by ssddanbrown** [comment]
Thanks for the request but the email script is only an example, not something I'm looking to add features to, so I'm going to close off this issue. 

Within the email script the ssl check output get's stored before read. Might be possible to search for the lack of `0 of` within the output text (Where is says `x of x domains expiring`) and use that as a conditional for the mailing.
